### ISSUE TITLE
Error on gnome 3.30.2

### ISSUE THREAD

**Issue by Ribodou** [mrEDitor/gnome-shell-extension-scroll-panel#14]
I am not able to run it on gnome 3.30.2 anymore after an update.
When I access the log (alf+f2, then type "lg", select "extensions" and "scroll panel"), all I get is "c.target.connect is not a function". The only occurrence of this code I could find is line 60  of extension.js. Unfortunately, I am not able to debug it myself yet.

**Comment by mrEDitor** [comment]
Hello! What Linux distribution do you use? And what is the version of extension? (You can check it out in `lg` or metadata file, if it is downloaded from extensions.gnome.org, I remember).
As a workaround, you might try:
- another extensions settings, especially two flags in the top of settings window, which change sensetive areas of top panel;
- extension [version for gnome 3.30](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/releases/tag/v3.2.0-gnome3.30) (in case you got fresher version and there is some backward compatibility problem).

Please, write back, if any of workarounds will help you. Thanks!

-----
UPD: most probably, the backward compatibility problem here: f79478da6956795324727dfdc2af731d128ff47e
If the second workaround will help, I might need to drop older gnome versions support from latest extension release.

**Comment by Ribodou** [comment]
Hello !
I am using debian stable and the version 10 of scroll panel. I couldn't find where to change the sensitive area, so I used the version you gave me (https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/releases/tag/v3.2.0-gnome3.30), and it worked !
If you have to drop support for older versions of gnome, is it possible to let users of those versions having access to scroll panel, by telling them to use an older version of your extension ?

**Comment by mrEDitor** [comment]
Yeah, my bad, I've accidentally dropped backward compatibility in latest release. My apologies for this!

Would you kindly try out fixed version? 
[v3.2.6-gnome3.36](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/tree/v3.2.6-gnome3.36) / [scroll-panel@mreditor.github.com.zip](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/files/4429759/scroll-panel%40mreditor.github.com.zip)
It should work on Gnome Shell 3.30 again.

**Comment by mrEDitor** [comment]
I've released fix as [v3.2.6-gnome3.36](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/releases/tag/v3.2.6-gnome3.36).
Feel free to reopen issue if any problems persist.
