### ISSUE TITLE
Scrolling for changing volume also changes panels, when enable together with Volume Mixer extension

### ISSUE THREAD

**Issue by inakil** [mrEDitor/gnome-shell-extension-scroll-panel#15]
Hi,
not sure if this is an issue of this extension or the Volume Mixer extension (https://extensions.gnome.org/extension/858/volume-mixer/). 
- With only Scroll Panel enabled, scrolling over the volume icon on the Status Menus allows to slide volume up or down as expected.
- When the Volume Mixer is also enabled toghether with Scroll Panel, trying to slide volume up or down using the scroll wheel on the Status Menu not only slide the volumes, but also scrolls the panel. 
Sorry if this issue isn't related to Scroll Panel, in that case fell free to delete this post. 
Thank you for the amazing extension.

Scroll Panel 5: v4.1.3+git-523f08f
Volume Mixer: not sure which version. Latest from Gnome Extension
Gnome Version: 40.4
Fedora 34

**Comment by mrEDitor** [comment]
@inakil hi and thank you for the feedback!

Indeed, this is the issue of volume-mixed extension, that does not reproduce with vanilla volume indicator. However it was not really obvious to implement the right way, the Gnome Shell and St do great and support such an edge case.

I've made a pull request to it, so you can try it out by building the patched version from scratch:
https://github.com/mrEDitor/gnome-shell-volume-mixer/tree/patch-1#installation

**Comment by inakil** [comment]
> @inakil hi and thank you for the feedback!
> 
> Indeed, this is the issue of volume-mixed extension, that does not reproduce with vanilla volume indicator. However it was not really obvious to implement the right way, the Gnome Shell and St do great and support such an edge case.
> 
> I've made a pull request to it, so you can try it out by building the patched version from scratch: https://github.com/mrEDitor/gnome-shell-volume-mixer/tree/patch-1#installation

I've tried the Volume Mixer patch-1 that you uploaded and it's working perfectly. Hope they merge it soon. Thanks.

Do you think I should write a comment in the Pull Request Conversation (https://github.com/aleho/gnome-shell-volume-mixer/pull/143) saying that I've tried and it works? Or that would be "bad etiquette" or superfluous?

**Comment by mrEDitor** [comment]
Glad it helped! 

> Do you think I should write a comment in the Pull Request Conversation ([aleho/gnome-shell-volume-mixer#143](https://github.com/aleho/gnome-shell-volume-mixer/pull/143)) saying that I've tried and it works? Or that would be "bad etiquette" or superfluous?

Huh, idk, I'm neither an expert in github etiquette. 😀
There is the link to this thread in the pull request, I suppose it's quite enough to see you've tried these extensions combination and it works.

**Comment by mrEDitor** [comment]
There may be more extensions which misinteract with Scroll Panel in such a way.
I pinned the issue so if it will be reproduced for other extensions by people with enough skills, it may be used to check the reason of misinteraction quickly: by patching problematic extension like I did in a [commit](https://github.com/aleho/gnome-shell-volume-mixer/pull/143) above.

**Comment by liquidev** [comment]
I just updated my system to GNOME 41.3 and it seems like this issue came back, but can now be reproduced with no extra extensions enabled.

**Comment by mrEDitor** [comment]
@liquidev and other, thank you for feedback, the problem is tracking under #20 now. Gnome 41.3 is not the source of problem, you may just downgrade the extension to previous version.
