### ISSUE TITLE
Allow to disable application scrolling

### ISSUE THREAD

**Issue by ai** [mrEDitor/gnome-shell-extension-scroll-panel#16]
Thanks for amazing and flexible extension.

I do not need to change application focus by mouse wheel.

Can we add a checkbox to disable `Switching windows`?

**Comment by mrEDitor** [comment]
Hello and thanks for feedback!

Please, consider disabling both scrolling surfaces (vertical and horizontal) for unused feature.

This use case is supposed to not introduce any shell state modifications related to unused feature; I'll check the implementation correctness later.

**Comment by ai** [comment]
> consider disabling both scrolling surfaces (vertical and horizontal) for unused feature.

Yeap, it works. Thanks.
