### ISSUE TITLE
GNOME 43 support

### ISSUE THREAD

**Issue by mimbrero** [mrEDitor/gnome-shell-extension-scroll-panel#26]
Hello!

Since GNOME 43 is now stable, when will this extension support it?

Thanks :)

**Comment by mrEDitor** [comment]
Hello! It's nearly here, thanks for waiting. For now:
- [x] source code updated;
- [x] I've tried it via Fedora 37 container a little bit;
- [x] pushed [to extensions.gnome.org](https://extensions.gnome.org/extension/4257/scroll-panel/), reviewed;
- [x] here is [v4.1.7-gnome43 release](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/releases/tag/v4.1.7-gnome43);
- [ ] Archlinux still waiting for Gnome 43, so I not using it on regular basis yet.

Known issues:
- [ ] podman script can't run Gnome 43 with X11 — does extension work on bare metal installations?
