### ISSUE TITLE
GNOME 44 support

### ISSUE THREAD

**Issue by yukina3230** [mrEDitor/gnome-shell-extension-scroll-panel#29]
Currently GNOME 44 alpha/beta has been released for testing, could you please take a look and port to GNOME 44.

Thanks for your work. This extension is very helpful to me.

**Comment by sstendahl** [comment]
Just FYI, if you go into the following folder:

`~/.local/share/gnome-shell/extensions/io.github.mreditor.gnome-shell-extensions.scroll-panel` (You can also reach it by heading to your home folder, pressing control+h, then going to local, share, gnome-shell, extensions and then to theio.github.mreditor.gnome-shell-extensions.scroll-panel folder)

And then open metadata.json and just add "44" to the supported shell lists, and then log out and log in again, it should all work on Gnome 44 without issues. At least it does on my machine. Many plug ins keep working through different shell versions, but this metadata still needs to be updated by the app developer each time to enable support for the latest Gnome Shell version. Hopefully there'll be a smoother solution to this at some point in the future, but don't expect this trick to work on every extension anyway.

Looking into the source code, it seems @mrEDitor already added this support by the way. So official GNOME 44 support will be there soon as we ll :)

**Comment by sstendahl** [comment]
Just as added info, as that may be relevant for the app developer.
I'm currently running Fedora 38 Silverblue on my machine (image from 2023-03-19) on bare metal in a Wayland session, running the latest (release candidate) version of GNOME 44. Haven't tested this on X11, if @mrEDitor wants to if he thinks it's relevant, I can do so. I don't think it matters, but it's a laptop with hybrid graphics (AMD iGPU, with an Nvidia RTX3050Ti dGPU) and a dual monitor setup, the HDMI slot that is used by the big external monitor (which is used as primary screen) is coupled to the Nvidia GPU.

I've only added "44" to the metadata of this extension, and it all works perfectly for me just like it did in GNOME 43. No other tweaks needed, so it seems like there's no breaking changes (for this extension) in gnome-shell this time.

**Comment by yukina3230** [comment]
Thank you, I added "44" to the metadata and it worked pretty well, and since mrEDitor has now added support for 44, I'm closing this issue.

**Comment by mrEDitor** [comment]
Thanks, guys, you're right, you can just add the 44 tag to metadata file to tell Gnome that extension is ready.
But there are some new requirements for extensions.gnome.org publishing, so the extension is not published there yet

**Comment by AlexWayfer** [comment]
> Thanks, guys, you're right, you can just add the 44 tag to metadata file to tell Gnome that extension is ready. But there are some new requirements for extensions.gnome.org publishing, so the extension is not published there yet

It's been a long time, 1.5 months, what's holding us?

**Comment by mrEDitor** [comment]
The reviewer guy rejected a fresh version since I've kept settings schema namespace (thinking of keeping user settings) untouched at first. Sorry, I don't have much sparse time for pet-projects currently, so updated it again just now.
