### ISSUE TITLE
3.20 support

### ISSUE THREAD

**Issue by sardaukar** [mrEDitor/gnome-shell-extension-scroll-panel#4]
Doable? :|

**Comment by ghost** [comment]
Already. Look at the https://github.com/mrEDitor/gnome-scroll-panel/commit/84ddea55169f2200c2ed90edac32e9829e206b66 of master.

**Comment by sardaukar** [comment]
Oh cool. The Extensions website tells me it's outdated, though. Do I need to install it manually?

On 25 June 2016 00:01:52 BST, Anna notifications@github.com wrote:

> Already. Look at the
> [HEAD~2](https://github.com/mrEDitor/gnome-scroll-panel/commit/84ddea55169f2200c2ed90edac32e9829e206b66)
> of master.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mrEDitor/gnome-scroll-panel/issues/4#issuecomment-228483988

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghost** [comment]
Yes, you can. It works for me.

**Comment by ghost** [comment]
Although, of course, it would be good to wait for the initiative of @mrEDitor .

**Comment by mrEDitor** [comment]
I've just reworked the extension and going to update it on extensions.gnome.org after some testing. If you want to try new version now, you can get it from [v3-gnome3.20](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/tree/v3-gnome3.20) branch.
