### ISSUE TITLE
Switch windows instead of workspaces by scrolling on empty space?

### ISSUE THREAD

**Issue by Deus-Rex** [mrEDitor/gnome-shell-extension-scroll-panel#5]
Not an issue, more of a suggestion. I don't use the feature to scroll workspaces using the empty topbar space and don't particularly like having to move my cursor to the application title to switch applications. I would find this extension much more useful if it could allow users to use the empty topbar space to switch applications as an additional option.

Heck, alternatively, how about middle clicking the topbar to switch applications or workspaces? That would be a decent solution as it would mean users don't have to decide on whether they use one feature over another. It would be much, much quicker to switch apps/workspaces by hovering the cursor over any part of the topbar and scrolling for workspaces, and middle clicking for applications.

I feel that the extension is brilliant, but could do with being more flexible in how it can be activated. Hope you take this into consideration.

**Comment by mrEDitor** [comment]
I totally agree that increasing flexibility would be a good improvement for the extension. I will consider your idea and try to implement some custom binding mechanics when I will have some time.
Thank you for idea and interest in extension.
-- Edward

**Comment by mystiquewolf** [comment]
I also +1 this. Activities hot corner makes it tricky to place the cursor over Activities button without triggering it overview. There is one other Gnome extension which uses free space to the left of the clock/date for windows, to the right of the clock for workspaces. But this one seems to remember the order of changed windows, not just scrolling through all of the windows like the other one.

**Comment by mrEDitor** [comment]
I've reworked the extension so you can setup precise panel on topbar for desired action, if you are still interested.

You can install it from scratches now, or wait for the v4 release after publishing on [extensions.gnome.org](https://extensions.gnome.org/extension/4257/scroll-panel/).
