### ISSUE TITLE
Show Workspace Switcher (as an option) like when using keys to switch workspaces

### ISSUE THREAD

**Issue by cyberalex4life** [mrEDitor/gnome-shell-extension-scroll-panel#7]
Not an issue, just a request, the way [Desktop Scroller by brorlandi](https://extensions.gnome.org/extension/561/desktop-scroller-all-sides-for-gnome-36/) does.

**Comment by mrEDitor** [comment]
It's a good idea, I've added the option to preferences of latest version (disabled by default).
Regretfully, it doesn't work well with switching windows, but looks pretty good for switching workspaces.

**Comment by cyberalex4life** [comment]
Thank you a lot!
