### ISSUE TITLE
Not working in GNOME Shell 3.30

### ISSUE THREAD

**Issue by jonnius** [mrEDitor/gnome-shell-extension-scroll-panel#8]
The extension is not working for me with GNOME Shell 3.30.1 on Ubuntu 18.10. Where do i find the log files?

**Comment by mrEDitor** [comment]
Hello!
Unfortunatelly, currently I do not have any working Gnome-based Linux desktop and free time, so I can't maintain the extension properly, but I'll try to do my best.

I suppose, you can find logs along with rest of Gnome extensinons logs in system journals, try searching output of `journalctl /usr/bin/gnome-session` or `journalctl /usr/lib/gnome-session/gnome-session-binary`.
Also you could try restarting Gnome Shell from terminal by `gnome-shell --replace`, so all logs will be printed out to terminal (I think then you will need restart it again by `gnome-shell --replace &` to detach it from terminal window).

And I recently saw comment about fixing extension for 3.30 at https://extensions.gnome.org/extension/1096/scroll-panel/ from 12 November by Untribium, may be it can help.

**Comment by mrEDitor** [comment]
Adapted for Gnome Shell 3.20, works for me. Feel free to reopen the issue, if it does not for you.

**Comment by jonnius** [comment]
Thanks!
